[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F42C08DD50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b388d47dc87918187dce0fc0bd7b7af8/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F42C08DED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b388d47dc87918187dce0fc0bd7b7af8/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F42C08E080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b388d47dc87918187dce0fc0bd7b7af8/element