[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F5D00F5E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a9186de8d9f059a8726e40030cc76ed3/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F5D00F760>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a9186de8d9f059a8726e40030cc76ed3/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F5D00F910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a9186de8d9f059a8726e40030cc76ed3/element