[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8EC1CDC30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7c14792d7146fed9005a027f4ae64472/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8EC1CDDB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7c14792d7146fed9005a027f4ae64472/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8EC1CDF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7c14792d7146fed9005a027f4ae64472/element