[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A24F85DCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3535e0e1f72b8aff28157f089b02fe24/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A24F85DE40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3535e0e1f72b8aff28157f089b02fe24/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A24F85DFF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3535e0e1f72b8aff28157f089b02fe24/element